version: '3.8'

services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:science98@postgres:5432/grocerydb

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: science98
      POSTGRES_DB: grocerydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
